/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

// source: tap.i

#ifndef SWIG_tap_WRAP_H_
#define SWIG_tap_WRAP_H_

class Swig_memory;

class SwigDirector_ITapQuoteAPINotify : public ITapQuoteAPINotify
{
 public:
  SwigDirector_ITapQuoteAPINotify(int swig_p);
  virtual void OnRspLogin(TAPIINT32 errorCode,TapAPIQuotLoginRspInfo const *info);
  virtual void OnAPIReady();
  virtual void OnDisconnect(TAPIINT32 reasonCode);
  virtual void OnRspQryCommodity(TAPIUINT32 sessionID,TAPIINT32 errorCode,TAPIYNFLAG isLast,TapAPIQuoteCommodityInfo const *info);
  virtual void OnRspQryContract(TAPIUINT32 sessionID,TAPIINT32 errorCode,TAPIYNFLAG isLast,TapAPIQuoteContractInfo const *info);
  virtual void OnRspSubscribeQuote(TAPIUINT32 sessionID,TAPIINT32 errorCode,TAPIYNFLAG isLast,TapAPIQuoteWhole const *info);
  virtual void OnRspUnSubscribeQuote(TAPIUINT32 sessionID,TAPIINT32 errorCode,TAPIYNFLAG isLast,TapAPIContract const *info);
  virtual void OnRtnQuote(TapAPIQuoteWhole const *info);
 private:
  intgo go_val;
  Swig_memory *swig_mem;
};

#endif
